### ISSUE TITLE
nsx-t-install pipeline doesn't be created

### ISSUE THREAD

**Issue by cdan** [vmware/nsx-t-datacenter-ci-pipelines#1]
Hi,
According to the README, I try this tool. But when login the concourse console there no pipeline. 
Error logs in the container:

_waiting for Concourse web server to be running
waiting for Concourse web server to be running
brought up the Concourse cluster
Creating concourse_concourse-worker_1 ... done
error: unknown target: nsx-concourse
logging in to team 'main'
target saved
setting the NSX-t install pipeline nsx-t-install
error: could not resolve template vars: yaml: line 104: did not find expected key
unpausing the pipepline nsx-t-install
pipeline 'nsx-t-install' not found_

Please help.

**Comment by kais66** [comment]
Hi,
The message "error: could not resolve template vars: yaml: line 104: did not find expected key" indicates there might be misconfiguration or typo in the parameter file nsx_pipeline_config.yml. Can you check line 104 of you parameter file against the sample?

**Comment by kais66** [comment]
Closing the issue since it seemed due to misconfiguration. Let us know if above suggestion didn't work for you.

**Comment by cdan** [comment]
It turns out this is related the parameter CONCOURSE_URL="http://10.33.75.99:8080" .
'http://' should be included.
