### ISSUE TITLE
No such file or directory error from install-nsx-t  task

### ISSUE THREAD

**Issue by tkrausjr** [vmware/nsx-t-datacenter-ci-pipelines#10]
I am receiving an error with the  Install-nsx-t  section of the pipeline when it goes to deploy the NSX Manager OVA – I am doing this with the OVA downloaded to /home/concourse on the machine where I run the Install Container(s).  This is a fairly vanilla installation so not sure what the issue is.

BTW –  Highlighted below does not look right to me. Should there be two backslashes in the VC heirarchy --@10.173.13.81//Datacenter/host/Nested-PKS/ ?
 
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/ovftool --acceptAllEulas --skipManifestCheck --X:injectOvfEnv --powerOn --noSSLVerify --allowExtraConfig --diskMode=thin --datastore=nfs-ubuntu-01 --name=nsxt-manager '--network=VM 1525' --prop:nsx_hostname=nsxt-mgr-23.tpmlab.vmware.com --prop:nsx_dns1_0=10.173.13.90 --prop:nsx_domain_0=tpmlab.vmware.com --prop:nsx_ntp_0=10.173.13.90 --prop:nsx_gateway_0=10.173.13.90 --prop:nsx_ip_0=10.173.13.82 --prop:nsx_netmask_0=255.255.255.0 '--prop:nsx_passwd_0=********' '--prop:nsx_cli_passwd_0=********' --prop:nsx_isSSHEnabled=True --prop:nsx_allowSSHRootLogin=True --prop:nsx_role=nsx-manager http://10.173.13.90:40001/nsx-unified-appliance-2.3.0.0.0.10085405.ova 'vi://administrator@vsphere.local:********@10.173.13.81//Datacenter/host/Nested-PKS/'", "msg": "[Errno 2] No such file or directory", "rc": 2}
                to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/basic_topology.retry

**Comment by tkrausjr** [comment]
I think I see the issue now. If I look in /home/concourse , some files are being generated.

r```oot@ubu01-jumphost:/home/concourse# ll
total 6254552
drwxr-xr-x 3 root root       4096 Oct 17 21:17 ./
drwxr-xr-x 5 root root       4096 Oct 17 20:19 ../
-rw-r--r-- 1 root root       1699 Oct 17 21:17 docker-compose.yml
-rwxr-xr-x 1 root root        358 Oct 17 21:17 generate-keys.sh*
drwxr-xr-x 4 root root       4096 Oct 17 12:53 keys/
-rw-r--r-- 1 root root       7606 Oct 17 21:08 nsx_pipeline_config.yml
-rw-r--r-- 1 root root 6368081920 Oct 16 17:21 nsx-unified-appliance-2.3.0.0.0.10085405.ova
-rw-r--r-- 1 root root        156 Oct 17 21:17 pipeline_config_internal.yml
-rw-r--r-- 1 root root   36536690 Oct 17 21:17 VMware-ovftool-4.3.0-10104578-lin.x86_64.bundle
```
If I look inside the pipeline_config_internal.yml (That I did not create). It shows the wrong name for the nsx-unified-appliance- Its showing the NSX 2.2 version but I downloaded 2.3 into /home/concourse and changed the parameter in my nsx_pipeline_config.yml  file.  So what is changing this entry in this file.

```
less pipeline_config_internal.yml

ovftool_file_name: VMware-ovftool-4.3.0-10104578-lin.x86_64.bundle
ova_file_name: nsx-unified-appliance-2.2.0.0.0.8680778.ova
nsx_t_pipeline_branch: master

```

**Comment by kais66** [comment]
Hi @tkrausjr 
The container will attempt to download ova and ovftool if either one is missing. In your case could it be the case where you didn't have ovftool under /home/concourse?
Now that you have both files, destroy and rerun the container. Make sure in your param file nsx_pipeline_config.yml you don't have the parameters ovftool_file_name and ova_file_name. They are supposed to be internal parameters and hidden.

**Comment by tkrausjr** [comment]
Doing all of the but my PARAMATERs file (nsx_pipeline_config.yml)  does have the two parameters set for OVA tool and NSX Manager. Ill try commenting them out and rerun.

**Comment by kais66** [comment]
Closing the issue since fix is already in. Let me know if the issue resurfaces.
