### ISSUE TITLE
Support fly command to update parameter values

### ISSUE THREAD

**Issue by tkrausjr** [vmware/nsx-t-datacenter-ci-pipelines#16]
Did some experimentation but is there a way to update the parameters file in /home/concourse and set the pipeline to use updated parameters without stopping / deleting / redeploying the entire docker image etc. ?

**Comment by NiranEC77** [comment]
See this 
https://github.com/vmware/nsx-t-datacenter-ci-pipelines/wiki/Operations

**Comment by kais66** [comment]
long story short, edit param file, then inside the docker container ,run "fly-reset".

**Comment by tkrausjr** [comment]
Thanks NIRAN !!! Sorry I didnt RTFM
