### ISSUE TITLE
Cluster host prep fails on random hosts within the cluster

### ISSUE THREAD

**Issue by nvpnathan** [vmware/nsx-t-datacenter-ci-pipelines#2]
Job: add-nsx-t-routers will fail to install and prep random hosts within the cluster. Workaround is you have to reboot and resolve each host that failed and then continue on with the pipeline.

**Comment by kais66** [comment]
@NiranEC77  Could this be due to the cert issue you were seeing?

**Comment by NiranEC77** [comment]
could be. Tested this in my lab and found that the "join" command on the failed host is using the wrong thumbprint:
/var/log/nsxcli.log:2018-10-05 02:08:44,513 73226 cli.audit INFO CMD: join management-plane 192.168.110.33 thumbprint ab9efaffd6c56f6f71c28d8d4e1cf476caf4efb1517e389642df24824ada8842 token <token-obfuscated> node-uuid e70d8fb8-9b90-45f0-ab59-cb9202816a1f (duration: 17.747s)

And the actual thumbprint 079d4a1bf92155cd52b6eb1302afda63813f34745e3655a179ea2c7c5ce68892

**Comment by kais66** [comment]
closing per the fix above. Please feel free to let us know if you see any issues with the fix.
