### ISSUE TITLE
NSX-T 2.4 deploy failure because of yml format error

### ISSUE THREAD

**Issue by lamlouis** [vmware/nsx-t-datacenter-ci-pipelines#33]
When deploying using the unified_appliance branch, I'm getting this error:

```
The error appears to have been in '/tmp/build/6fab756d/nsxt-ansible/basic_topology.yml': line 283, column 15, but may
	
be elsewhere in the file depending on the exact syntax problem.
	
The offending line appears to be:
	
            dns_servers: ["{{hostvars['localhost'].dns_server}}"]	
              enable_ssh: "{{hostvars['localhost'].nsx_manager_ssh_enabled}}"	
              ^ here
```

I tracked the error to `tasks/install-nsx-t/task.sh` line 78-80
```
    # DNS server needs to be specified for static IPs
    DNS_SERVER="\"{{hostvars[\'localhost\'].dns_server}}\""
    sed -i "/hostvars\[item\].prefix_length/a \ \ \ \ \ \ \ \ \ \ \ \ dns_servers: [$DNS_SERVER]" basic_topology.yml```
```

In nsxt_yaml/basic_topology.yml line 283, the `nsxt_transport_nodes` has one extra level of indentation, causing the sed substitution to be off.

**Comment by Dyanngg** [comment]
Hi @lamlouis 
Thanks for raising this issue. It is fixed now in latest commit on 'unified_appliance' branch.

**Comment by Dyanngg** [comment]
Closing this issue as resolved. 'unified_appliance' branch has been renamed nsxt_2.4.0.
