### ISSUE TITLE
concourse web server is missing due to no keys generated

### ISSUE THREAD

**Issue by lxiaopei** [vmware/nsx-t-datacenter-ci-pipelines#39]
root@prme-hs2-nsbu2-dhcp-001-101:/home/concourse# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                   PORTS                   NAMES
c05a0eec44f6        concourse/concourse:4.2.1   "/usr/local/bin/du..."   2 hours ago         Up 2 hours                                       concourse_concourse-worker_1
17c6f0dfcaf2        concourse/concourse:4.2.1   "/usr/local/bin/du..."   2 hours ago         Exited (2) 2 hours ago                           concourse_concourse-web_1
ef90e5dcbe47        postgres                    "docker-entrypoint..."   2 hours ago         Up 2 hours               5432/tcp                concourse_concourse-db_1
fb7ff0778e01        nginx                       "nginx -g 'daemon ..."   2 hours ago         Up 2 hours               0.0.0.0:40001->80/tcp   nginx-server
678cde5a5fc0        nsx-t-install               "/home/run.sh"           2 hours ago         Up 2 hours                                       silly_hopper
root@prme-hs2-nsbu2-dhcp-001-101:/home/concourse# docker logs 17c6f0dfcaf2
{"timestamp":"1554879222.426381826","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.18.0.2:5432: connect: connection refused","session":"3"}}
{"timestamp":"1554879227.429934263","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.18.0.2:5432: connect: connection refused","session":"3"}}
{"timestamp":"1554879234.984454870","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys expired, rotating","session":"5"}}
{"timestamp":"1554879235.563573599","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"keys rotated, next rotation: 2019-04-10 12:53:55.561769806 +0000 UTC m=+21615.800778077","session":"5"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe3485]
 
goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/rsa/rsa.go:100 +0x5
golang.org/x/crypto/ssh.NewSignerFromSigner(0x7fd4ba095578, 0xc00000e318, 0xc00000e318, 0x7fd4ba095578, 0xc00000e318, 0xe8af01)
        /tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:681 +0x35
golang.org/x/crypto/ssh.NewSignerFromKey(0x2a2eb40, 0xc00000e318, 0xe8afc8, 0x30, 0x2b17180, 0xc000849408)
        /tmp/build/9674af12/concourse/src/golang.org/x/crypto/ssh/keys.go:656 +0x16a
github.com/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer(0xc000935290, 0xc0004e90f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000196700, 0x7, ...)
        /tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:197 +0x167
github.com/concourse/tsa/tsacmd.(*TSACommand).Runner(0xc000935290, 0xc000512900, 0x0, 0x1, 0x17dbe900, 0xc00082a640, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/concourse/tsa/tsacmd/command.go:95 +0x249
main.(*WebCommand).Runner(0xc000ae4a08, 0xc000512900, 0x0, 0x1, 0x2, 0x5, 0xc0005127a0, 0xc000ebe000)
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:67 +0x132
main.(*WebCommand).Execute(0xc000ae4a08, 0xc000512900, 0x0, 0x1, 0x28fde00, 0x2b848a0)
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/web.go:42 +0x5c
github.com/vito/twentythousandtonnesofcrudeoil.installEnv.func2(0x7fd4ba06a140, 0xc000ae4a08, 0xc000512900, 0x0, 0x1, 0x1, 0xc00064b7e8)
        /tmp/build/9674af12/concourse/src/github.com/vito/twentythousandtonnesofcrudeoil/environment.go:40 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000ece300, 0xc00000c070, 0x1, 0x1, 0xc00064b880, 0x20fe6bf, 0xc000ece300, 0x2bc8013, 0xa)
        /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x7bc
github.com/jessevdk/go-flags.(*Parser).Parse(0xc000ece300, 0x2bc8013, 0xa, 0xc00002b700, 0x0, 0x0)
        /tmp/build/9674af12/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /tmp/build/9674af12/concourse/src/github.com/concourse/bin/cmd/concourse/main.go:33 +0x19e

**Comment by Dyanngg** [comment]
Hi @lxiaopei this issue is resolved with recent commits across all branches, and the docker images are updated to reflect the change as well. Thanks for bringing the update up!
