### ISSUE TITLE
hostname set without suffix; certs generated with wrong hostname

### ISSUE THREAD

**Issue by cunnie** [vmware/nsx-t-datacenter-ci-pipelines#45]
On branch `nsxt_2.4.0`, the hostname is set without the suffix (i.e. `-1`):

On `nsx_pipe_config.yml`:
```yaml
nsx_manager_hostname_prefix: "nsxmgr" # Generated hostname: nsxt-mgr-1.corp.local.io, will be FQDN
```
The machine is deployed as `nsxmgr-1` (expected), but thinks its hostname is `nsxmgr` (unexpected) (from NSX-T Manager CLI):
```
nsxmgr> get hostname
nsxmgr
```
Also, two of the certificates are set for the wrong hostname (see attached screenshot)
<img width="1060" alt="wrong_cert_names" src="https://user-images.githubusercontent.com/1020675/56537557-b6606500-6515-11e9-94fe-90db1ff789ec.png">

**Comment by NiranEC77** [comment]
Brian, don't use the 2.4 branch. Use master it will install the latest. we will remove that branch

**Comment by Dyanngg** [comment]
Hi Brian,
Thanks for bringing the issue up! This error should be fixed in the latest commit on both master and nsxt_2.4.0.

**Comment by cunnie** [comment]
Thanks @NiranEC77 — we'll tear down our environment & rebuild with the master branch.
