### ISSUE TITLE
Problem installing iputils-ping when installing nsx

### ISSUE THREAD

**Issue by lxiaopei** [vmware/nsx-t-datacenter-ci-pipelines#49]
Hi, 

Logs as below, I checked the nsx-t-install image is using ubuntu 17.10, which met the below issue. 
I manually tried to use Ubuntu 16.04 and no such issue. 
Could we consider to use Ubuntu 16.04?

ASK [Install ping] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/build/6fab756d/nsxt-ansible/basic_topology.yml:188
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062 `" && echo ansible-tmp-1557215846.65-193737253420062="` echo /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt.py
<localhost> PUT /root/.ansible/tmp/ansible-local-142cVoCGw/tmpfrEwyD TO /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062/apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062/ /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062/apt.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062/apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1557215846.65-193737253420062/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_M8XD1j/ansible_module_apt.py", line 299, in <module>
    import apt
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": "apt-get update", 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoclean": false, 
            "autoremove": false, 
            "cache_valid_time": 0, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "force_apt_get": false, 
            "install_recommends": null, 
            "name": "iputils-ping", 
            "only_upgrade": false, 
            "package": [
                "iputils-ping"
            ], 
            "purge": false, 
            "state": "present", 
            "update_cache": null, 
            "upgrade": null
        }
    }, 
    "msg": "E: The repository 'http://security.ubuntu.com/ubuntu artful-security Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful-updates Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful-backports Release' no longer has a Release file.", 
    "rc": 100, 
    "stderr": "E: The repository 'http://security.ubuntu.com/ubuntu artful-security Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful-updates Release' no longer has a Release file.\nE: The repository 'http://archive.ubuntu.com/ubuntu artful-backports Release' no longer has a Release file.\n", 
    "stderr_lines": [
        "E: The repository 'http://security.ubuntu.com/ubuntu artful-security Release' no longer has a Release file.", 
        "E: The repository 'http://archive.ubuntu.com/ubuntu artful Release' no longer has a Release file.", 
        "E: The repository 'http://archive.ubuntu.com/ubuntu artful-updates Release' no longer has a Release file.", 
        "E: The repository 'http://archive.ubuntu.com/ubuntu artful-backports Release' no longer has a Release file."
    ], 
    "stdout": "Ign:1 http://archive.ubuntu.com/ubuntu artful InRelease\nIgn:2 http://security.ubuntu.com/ubuntu artful-security InRelease\nHit:3 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease\nIgn:4 http://archive.ubuntu.com/ubuntu artful-updates InRelease\nErr:5 http://security.ubuntu.com/ubuntu artful-security Release\n  404  Not Found [IP: 91.189.88.152 80]\nIgn:6 http://archive.ubuntu.com/ubuntu artful-backports InRelease\nErr:7 http://archive.ubuntu.com/ubuntu artful Release\n  404  Not Found [IP: 91.189.88.162 80]\nErr:8 http://archive.ubuntu.com/ubuntu artful-updates Release\n  404  Not Found [IP: 91.189.88.162 80]\nErr:9 http://archive.ubuntu.com/ubuntu artful-backports Release\n  404  Not Found [IP: 91.189.88.162 80]\nReading package lists...\n", 
    "stdout_lines": [
        "Ign:1 http://archive.ubuntu.com/ubuntu artful InRelease", 
        "Ign:2 http://security.ubuntu.com/ubuntu artful-security InRelease", 
        "Hit:3 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease", 
        "Ign:4 http://archive.ubuntu.com/ubuntu artful-updates InRelease", 
        "Err:5 http://security.ubuntu.com/ubuntu artful-security Release", 
        "  404  Not Found [IP: 91.189.88.152 80]", 
        "Ign:6 http://archive.ubuntu.com/ubuntu artful-backports InRelease", 
        "Err:7 http://archive.ubuntu.com/ubuntu artful Release", 
        "  404  Not Found [IP: 91.189.88.162 80]", 
        "Err:8 http://archive.ubuntu.com/ubuntu artful-updates Release", 
        "  404  Not Found [IP: 91.189.88.162 80]", 
        "Err:9 http://archive.ubuntu.com/ubuntu artful-backports Release", 
        "  404  Not Found [IP: 91.189.88.162 80]", 
        "Reading package lists..."
    ]
}
	to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/basic_topology.retry

**Comment by Dyanngg** [comment]
Hi @lxiaopei ,
Thanks for raising the issue. The problem comes from the fact that nsx-t-install image and the image used for fulfilling ansible tasks (nsx-t-gen-worker) are all built from ubuntu 17.10, which has now been obsolete. I have pushed a new image to dyanngg/nsx-t-gen-worker. Since nsx-t-gen-worker has golang dependency >= 1.8, ubuntu 18.04 is needed so for consistency I'm upgrading nsx-t-install image to 18.04 as well. Please see to the latest patch on nsx_2.4.0.

**Comment by wbean1** [comment]
could we get this on the `nsx_2.3.0` branch as well?

**Comment by Dyanngg** [comment]
Closing this issue as ubuntu image update is done for all active branches
