### ISSUE TITLE
Sample config missing param definitions

### ISSUE THREAD

**Issue by aegershman** [vmware/nsx-t-datacenter-ci-pipelines#51]
After filling out the sample config from `sample_parameters/PAS_and_PKS/nsx_pipeline_config.yml` and `fly`'ing up the pipeline, the pipeline complained of missing params for the following:

```yml
nsxt_ansible_branch
nsx_t_pipeline_branch
ova_file_name
ovftool_file_name
```

It would be very helpful to have default values included in the sample config and described with a comment, as I'm not sure what the values like the branches should be (master?)

EDIT: I see. These params are defined in [the `docker_image/run.sh`](https://github.com/vmware/nsx-t-datacenter-ci-pipelines/blob/master/docker_image/run.sh#L72-L76) but they're not in the sample_config, which makes it confusing when using the "existing Concourse" workflow

**Comment by Dyanngg** [comment]
@aegershman Thanks for pointing this out. Doc has been updated on that regard.

**Comment by aegershman** [comment]
Would you accept a PR which adds these keys to the [nsx_pipeline_config](https://github.com/vmware/nsx-t-datacenter-ci-pipelines/blob/master/sample_parameters/PAS_and_PKS/nsx_pipeline_config.yml)? (or have someone vmware-side add it themselves?)

Even if they're commented out in the sample_params file, it makes it easier to understand all the values that are required.

**Comment by Dyanngg** [comment]
@aegershman For this pipeline, we recommend using the docker image provided to fly up concourse, which takes care of these params by default. If using the docker image and specifying conflicting param in the config file, the pipeline will run into erroneous state. Thus we prefer leave how to manually configure these in the documentation.

**Comment by aegershman** [comment]
@Dyanngg Right though the [wiki has a section on how to use the pipeline with an existing Concourse](https://github.com/vmware/nsx-t-datacenter-ci-pipelines/wiki/Configuring-the-pipeline-to-run-on-an-existing-Concourse-server) rather than using the docker image

We were having unpleasant problems using the Docker method to run this locally because [the docker_image/run.sh tried to ./generate-keys using the docker-compose from concourse-docker `master` and it was barfing with errors, though it looks like this was fixed two days ago](https://github.com/vmware/nsx-t-datacenter-ci-pipelines/commit/fde80abab0acef6f42f6f3979a06426959e9b185)-- and honestly the only reason we ran it with the Docker method was because it seems it was the only supported way for the pipeline to consume the `*.ova` and `*.bundle` is [how it's served up over nginx via docker](https://github.com/vmware/nsx-t-datacenter-ci-pipelines/blob/master/docker_image/run.sh#L79)

I guess what I'm saying is, it'll likely make things easier for both consumers and repo maintainers if the required parameters are defined in the code itself rather than the wiki. It'll help reduce drift.

Will stop pushing on this specific issue but in general hope vmware considers moving the usage doc out of the wiki and into the code/params itself
