### ISSUE TITLE
I am still getting error as these entries are missing where I already have these on /home/concoruse/nsx_pipeline_config.yml

### ISSUE THREAD

**Issue by sarojraju** [vmware/nsx-t-datacenter-ci-pipelines#64]
Entries : 

nsxt_ansible_branch: v1.0.0
nsx_t_pipeline_branch: nsxt_2.3.0
ova_file_name: nsx-unified-appliance-2.4.0.0.0.12456291.ova
ovftool_file_name: VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle

**Comment by Dyanngg** [comment]
Hi @sarojraju,
Can you share if you are using the docker image in this rep to setup concourse, or if you are using an existing concourse server? In the first case, you do not need to set these params.

**Comment by sarojraju** [comment]
I am using my existing concourse server instead of docker image concourse.

**Comment by Dyanngg** [comment]
As discussed offline I believe this issue should be resolved.
