### ISSUE TITLE
ESXi hosts timeout on NSX-T install

### ISSUE THREAD

**Issue by jhency** [vmware/nsx-t-datacenter-ci-pipelines#7]
After Concourse pipeline completed with all green boxes, ESXi hosts show NSX-T install failed from the Nodes pane in NSX-T GUI.

**Comment by nvpnathan** [comment]
Jerry this is the same issue I'm seeing as well.

https://github.com/vmware/nsx-t-datacenter-ci-pipelines/issues/2

**Comment by jhency** [comment]
A little different maybe, my NSX-T pipeline completed all green. Only noticed the host install fail when I looked around through the GUI to see what the pipeline had done. I corrected the install issue just by hitting "resolve" on each of the hosts in the NSX-T GUI.

**Comment by NiranEC77** [comment]
Issue should be fixed now. Can you run a test?

**Comment by kais66** [comment]
merged https://github.com/vmware/nsx-t-datacenter-ci-pipelines/pull/8 to address this issue.

**Comment by kais66** [comment]
closing per the fix above. Please feel free to let us know if you see any issues with the fix.

**Comment by garreeoke** [comment]
We had the same issue while running the pipeline today.  Pipeline was green, but 5 out of 6 hosts failed installation of NSX.

**Comment by sudhakarau1** [comment]
ran into same issue running pipeline
